# Generated by Django 5.1.3 on 2025-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Контент")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalog/images/",
                        verbose_name="фотография продукта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Заголовок",
                "verbose_name_plural": "Заголовки",
                "ordering": ["-created_at"],
            },
        ),
    ]
