# Generated by Django 5.1.3 on 2025-01-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
