# Generated by Django 5.1.3 on 2025-01-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
    ]
