# Generated by Django 5.1.3 on 2025-01-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Укажите, опубликован ли продукт",
                verbose_name="опубликован",
            ),
        ),
    ]
