# Generated by Django 5.1.3 on 2025-01-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "price", "created_at", "updated_at"],
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта")
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
